# Generated by Django 5.2 on 2025-04-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_units', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserShareSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user_id', models.IntegerField()),
                ('units_held', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'unique_together': {('date', 'user_id')},
            },
        ),
    ]
