# Generated by Django 4.2.23 on 2025-08-02 17:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_units', models.DecimalField(decimal_places=8, max_digits=20)),
                ('nav_per_unit', models.DecimalField(decimal_places=8, default=Decimal('1.0'), max_digits=20)),
                ('gain_or_loss', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('cash', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('portfolio_total_value', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('net_inflows', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserShareSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user_id', models.IntegerField()),
                ('units_held', models.DecimalField(decimal_places=8, max_digits=20)),
                ('value_held', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
            ],
            options={
                'unique_together': {('date', 'user_id')},
            },
        ),
    ]
