# Generated by Django 5.2 on 2025-05-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_valuation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersharesnapshot',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
