# Generated by Django 5.2 on 2025-05-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_valuation', '0002_alter_usersharesnapshot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersharesnapshot',
            name='date',
            field=models.DateField(),
        ),
    ]
