# Generated by Django 5.2 on 2025-05-05 19:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_valuation', '0003_alter_usersharesnapshot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyportfoliosnapshot',
            name='nav_per_unit',
            field=models.DecimalField(decimal_places=8, default=Decimal('1.0'), max_digits=20),
        ),
    ]
