# Generated by Django 5.2 on 2025-05-11 19:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_valuation', '0004_dailyportfoliosnapshot_nav_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyportfoliosnapshot',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='dailyportfoliosnapshot',
            name='gain_or_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='dailyportfoliosnapshot',
            name='net_inflows',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='dailyportfoliosnapshot',
            name='portfolio_total_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20),
        ),
    ]
