# Generated by Django 5.2 on 2025-05-12 16:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_valuation', '0005_dailyportfoliosnapshot_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersharesnapshot',
            name='value_held',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20),
        ),
    ]
