# Generated by Django 4.2.19 on 2025-03-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprice',
            old_name='timestamp',
            new_name='date',
        ),
    ]
