# Generated by Django 4.2.19 on 2025-03-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0003_historicalexchangerate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalExchangeRate',
        ),
    ]
