# Generated by Django 4.2.19 on 2025-03-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0004_delete_historicalexchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPriceEnriched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('open', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('open_euro', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('high_euro', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('low_euro', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('close_euro', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
