# Generated by Django 4.2.19 on 2025-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0005_historicalpriceenriched'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseHistoricalExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('open', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
