# Generated by Django 5.2 on 2025-04-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0007_tickerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprice',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
