# Generated by Django 5.2 on 2025-04-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0008_historicalprice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprice',
            name='close_euro',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalprice',
            name='high_euro',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalprice',
            name='low_euro',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalprice',
            name='open_euro',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
