# Generated by Django 5.2 on 2025-04-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0009_historicalprice_close_euro_historicalprice_high_euro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPriceEnriched',
        ),
    ]
