# Generated by Django 5.2 on 2025-05-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0011_alter_historicalprice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehistoricalexchangerate',
            name='date',
            field=models.DateField(),
        ),
    ]
