# Generated by Django 5.2 on 2025-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0012_alter_basehistoricalexchangerate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerinfo',
            name='market_cap',
            field=models.BigIntegerField(null=True),
        ),
    ]
