# Generated by Django 5.2.4 on 2025-08-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VARComputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('var_95', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('var_99', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('expected_shortfall_95', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('expected_shortfall_99', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
