# Generated by Django 5.2.4 on 2025-08-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varcomputation',
            old_name='expected_shortfall_95',
            new_name='expected_shortfall_95_10day',
        ),
        migrations.RenameField(
            model_name='varcomputation',
            old_name='expected_shortfall_99',
            new_name='expected_shortfall_95_1day',
        ),
        migrations.RenameField(
            model_name='varcomputation',
            old_name='var_95',
            new_name='expected_shortfall_95_5day',
        ),
        migrations.RenameField(
            model_name='varcomputation',
            old_name='var_99',
            new_name='expected_shortfall_99_10day',
        ),
        migrations.AddField(
            model_name='varcomputation',
            name='expected_shortfall_99_1day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='varcomputation',
            name='expected_shortfall_99_5day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='varcomputation',
            name='var_95_10day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='varcomputation',
            name='var_95_1day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='varcomputation',
            name='var_95_5day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='varcomputation',
            name='var_99_10day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='varcomputation',
            name='var_99_1day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='varcomputation',
            name='var_99_5day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
