# Generated by Django 5.2.4 on 2025-08-26 13:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_valuation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyportfoliosnapshot',
            name='nav_returns',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=10),
        ),
    ]
