# Generated by Django 5.2.4 on 2025-08-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_valuation', '0002_dailyportfoliosnapshot_nav_returns'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCompositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=32)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('value_eur', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'unique_together': {('date', 'ticker')},
            },
        ),
    ]
