# Generated by Django 5.2.4 on 2025-08-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprice',
            name='nav',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
